name: onlineradiosearchmobile
description: Online Radio Search App

publish_to: 'none'
version: 1.0.0+18

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^1.4.0
  flutter_spinkit: ^5.0.0
  just_audio: ^0.6.15+1
  rxdart: ^0.25.0
  flutter_cache_manager: ">= 1.4.0 < 3.0.0"
  flutter_isolate: ^1.0.0+14
  audio_service: ^0.16.2
  provider: ^5.0.0
  optional: ^5.0.0+1
  flutter_launcher_icons: ^0.8.1
  audio_session: ^0.0.11
  uuid: ">=2.0.0"
  sqflite:
  path:
  cupertino_icons: ^1.0.2
  google_mobile_ads: ^0.11.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: 'icon/icon.png'
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/
