name: Flutter CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1.3.2

      with:
        flutter-version: '1.22.0'
      env:
        KEY_JKS: ${{ secrets.KEY_JKS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        ALIAS_PASSWORD: ${{ secrets.STORE_PASSWORD }}
    - run: echo $KEY_JKS > key.jks
    - run: cat key.jks
    - run: flutter doctor
    - run: flutter pub get
    - run: flutter test
    - run: flutter build apk
